import { DataSource } from 'typeorm';
import { PropertyDetails } from 'src/main/entities/property-details.entity';
import { User } from 'src/main/entities/user.entity';

export const seedPropertyDetails = async (
  dataSource: DataSource,
): Promise<void> => {
  const propertyDetailsRepository = dataSource.getRepository(PropertyDetails);
  const userRepository = dataSource.getRepository(User);

  const adminUser = await userRepository.findOne({ where: { id: 1 } });

  if (!adminUser) {
    throw new Error(
      'Admin user must be seeded before seeding property details',
    );
  }

  const existingPropertyDetails = await propertyDetailsRepository.find();
  if (existingPropertyDetails.length === 0) {
    const propertyDetailsData = [
      {
        property: { id: 1 },
        createdBy: adminUser,
        noOfGuestsAllowed: 24,
        noOfBedrooms: 8,
        noOfBathrooms: 9,
        noOfBathroomsFull: 9,
        noOfBathroomsHalf: 0,
        squareFootage: '5300',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 600,
        noOfPetsAllowed: 2,
        petPolicy: 'Pets Allowed',
        feePerPet: 0,
        peakSeasonStartDate: new Date('2024-03-15'),
        peakSeasonEndDate: new Date('2024-06-28'),
        peakSeasonAllottedNights: 14,
        offSeasonAllottedNights: 30,
        peakSeasonAllottedHolidayNights: 1,
        offSeasonAllottedHolidayNights: 1,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: 'QuantumFiber8362',
      },
      {
        property: { id: 2 },
        createdBy: adminUser,
        noOfGuestsAllowed: 24,
        noOfBedrooms: 8,
        noOfBathrooms: 9,
        noOfBathroomsFull: 9,
        noOfBathroomsHalf: 0,
        squareFootage: '5300',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 600,
        noOfPetsAllowed: 2,
        petPolicy: 'Pets Allowed',
        feePerPet: 0,
        peakSeasonStartDate: new Date('2024-03-15'),
        peakSeasonEndDate: new Date('2024-06-28'),
        peakSeasonAllottedNights: 10,
        offSeasonAllottedNights: 27,
        peakSeasonAllottedHolidayNights: 1,
        offSeasonAllottedHolidayNights: 1,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: 'QuantumFiber8362',
      },
      {
        property: { id: 3 },
        createdBy: adminUser,
        noOfGuestsAllowed: 14,
        noOfBedrooms: 4,
        noOfBathrooms: 5,
        noOfBathroomsFull: 4,
        noOfBathroomsHalf: 1,
        squareFootage: '2200',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 210,
        noOfPetsAllowed: 2,
        petPolicy: 'Pets Allowed',
        feePerPet: 50,
        peakSeasonStartDate: new Date('2024-03-20'),
        peakSeasonEndDate: new Date('2024-07-09'),
        peakSeasonAllottedNights: 14,
        offSeasonAllottedNights: 30,
        peakSeasonAllottedHolidayNights: 1,
        offSeasonAllottedHolidayNights: 1,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: 'CenturyLink2149_5G and/or CenturyLink2149_2.4G',
      },
      {
        property: { id: 4 },
        createdBy: adminUser,
        noOfGuestsAllowed: 32,
        noOfBedrooms: 7,
        noOfBathrooms: 10,
        noOfBathroomsFull: 10,
        noOfBathroomsHalf: 0,
        squareFootage: '6200',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 575,
        noOfPetsAllowed: 2,
        petPolicy: 'Pets Allowed',
        feePerPet: 0,
        peakSeasonStartDate: new Date('2024-03-20'),
        peakSeasonEndDate: new Date('2024-06-18'),
        peakSeasonAllottedNights: 7,
        offSeasonAllottedNights: 21,
        peakSeasonAllottedHolidayNights: 1,
        offSeasonAllottedHolidayNights: 1,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: 'QuantumFiber1150',
      },
      {
        property: { id: 5 },
        createdBy: adminUser,
        noOfGuestsAllowed: 9,
        noOfBedrooms: 3,
        noOfBathrooms: 3,
        noOfBathroomsFull: 3,
        noOfBathroomsHalf: 0,
        squareFootage: '2075',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 185,
        noOfPetsAllowed: 2,
        petPolicy: 'Pets Allowed',
        feePerPet: 50,
        peakSeasonStartDate: new Date('2024-06-01'),
        peakSeasonEndDate: new Date('2024-09-20'),
        peakSeasonAllottedNights: 14,
        offSeasonAllottedNights: 30,
        peakSeasonAllottedHolidayNights: 1,
        offSeasonAllottedHolidayNights: 1,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: 'Blue Bear Lake',
      },
      {
        property: { id: 6 },
        createdBy: adminUser,
        noOfGuestsAllowed: 16,
        noOfBedrooms: 5,
        noOfBathrooms: 4,
        noOfBathroomsFull: 4,
        noOfBathroomsHalf: 0,
        squareFootage: '3500',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 365,
        noOfPetsAllowed: 2,
        petPolicy: 'Pets Allowed',
        feePerPet: 50,
        peakSeasonStartDate: new Date('2024-06-01'),
        peakSeasonEndDate: new Date('2024-09-20'),
        peakSeasonAllottedNights: 14,
        offSeasonAllottedNights: 30,
        peakSeasonAllottedHolidayNights: 1,
        offSeasonAllottedHolidayNights: 1,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: 'The Lakehouse',
      },
      {
        property: { id: 7 },
        createdBy: adminUser,
        noOfGuestsAllowed: 18,
        noOfBedrooms: 6,
        noOfBathrooms: 4,
        noOfBathroomsFull: 4,
        noOfBathroomsHalf: 0,
        squareFootage: '4300',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 365,
        noOfPetsAllowed: 0,
        petPolicy: 'No Pets Allowed',
        feePerPet: 50,
        peakSeasonStartDate: new Date('2024-06-01'),
        peakSeasonEndDate: new Date('2024-09-20'),
        peakSeasonAllottedNights: 14,
        offSeasonAllottedNights: 30,
        peakSeasonAllottedHolidayNights: 1,
        offSeasonAllottedHolidayNights: 1,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: 'Lake House',
      },
      {
        property: { id: 8 },
        createdBy: adminUser,
        noOfGuestsAllowed: 11,
        noOfBedrooms: 3,
        noOfBathrooms: 3,
        noOfBathroomsFull: 3,
        noOfBathroomsHalf: 0,
        squareFootage: '2075',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 0,
        noOfPetsAllowed: 0,
        petPolicy: 'No Pets Allowed',
        feePerPet: 0,
        peakSeasonStartDate: new Date('2024-06-01'),
        peakSeasonEndDate: new Date('2024-09-20'),
        peakSeasonAllottedNights: 14,
        offSeasonAllottedNights: 30,
        peakSeasonAllottedHolidayNights: 1,
        offSeasonAllottedHolidayNights: 1,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: 'Huckleberry House',
      },
      {
        property: { id: 9 },
        createdBy: adminUser,
        noOfGuestsAllowed: 35,
        noOfBedrooms: 6,
        noOfBathrooms: 5,
        noOfBathroomsFull: 5,
        noOfBathroomsHalf: 0,
        squareFootage: '4764',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 0,
        noOfPetsAllowed: 2,
        petPolicy: 'Pets Allowed',
        feePerPet: 50,
        peakSeasonStartDate: new Date('2024-06-01'),
        peakSeasonEndDate: new Date('2024-09-20'),
        peakSeasonAllottedNights: 0,
        offSeasonAllottedNights: 0,
        peakSeasonAllottedHolidayNights: 0,
        offSeasonAllottedHolidayNights: 0,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: '',
      },
      {
        property: { id: 10 },
        createdBy: adminUser,
        noOfGuestsAllowed: 11,
        noOfBedrooms: 3,
        noOfBathrooms: 3,
        noOfBathroomsFull: 2,
        noOfBathroomsHalf: 1,
        squareFootage: '1515',
        checkInTime: 16,
        checkOutTime: 11,
        cleaningFee: 0,
        noOfPetsAllowed: 2,
        petPolicy: 'Pets Allowed',
        feePerPet: 0,
        peakSeasonStartDate: new Date('2024-06-01'),
        peakSeasonEndDate: new Date('2024-09-20'),
        peakSeasonAllottedNights: 14,
        offSeasonAllottedNights: 30,
        peakSeasonAllottedHolidayNights: 1,
        offSeasonAllottedHolidayNights: 1,
        lastMinuteBookingAllottedNights: 8,
        wifiNetwork: '',
      },
    ];

    const propertyDetailsEntities = propertyDetailsData.map((details) =>
      propertyDetailsRepository.create(details),
    );

    await propertyDetailsRepository.save(propertyDetailsEntities);
  }
};
