import { UserProperties } from 'src/main/entities/user-properties.entity';
import { DataSource } from 'typeorm';

export const seedUserPropertyDetails = async (
  datasource: DataSource,
): Promise<void> => {
  const userPropertyDetails = datasource.getRepository(UserProperties);

  const existingUserPropertyDetails = await userPropertyDetails.find();
  if (existingUserPropertyDetails.length === 0) {
    await userPropertyDetails.save([
      {
        user: { id: 2 },
        property: { id: 1 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2024,
        peakAllottedNights: 0,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 0,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 30,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 30,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 2 },
        property: { id: 1 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2025,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 30,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 30,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 2 },
        property: { id: 1 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2026,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 30,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 30,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 2 },
        property: { id: 2 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2024,
        peakAllottedNights: 0,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 0,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 27,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 27,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 2 },
        property: { id: 2 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2025,
        peakAllottedNights: 10,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 10,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 27,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 27,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 2 },
        property: { id: 2 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2026,
        peakAllottedNights: 10,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 10,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 27,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 27,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 2 },
        property: { id: 3 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2024,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 30,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 30,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 2 },
        property: { id: 3 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2025,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 30,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 30,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 2 },
        property: { id: 3 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2026,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 30,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 30,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 3 },
        property: { id: 4 },
        noOfShare: 2,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2024,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 42,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 42,
        offAllottedHolidayNights: 2,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 2,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 16,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 16,
        maximumStayLength: 21,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 3 },
        property: { id: 4 },
        noOfShare: 2,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2025,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 42,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 42,
        offAllottedHolidayNights: 2,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 2,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 16,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 16,
        maximumStayLength: 21,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 3 },
        property: { id: 4 },
        noOfShare: 2,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2026,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 42,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 42,
        offAllottedHolidayNights: 2,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 2,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 16,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 16,
        maximumStayLength: 21,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 3 },
        property: { id: 6 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2024,
        peakAllottedNights: 0,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 0,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 30,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 30,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 3 },
        property: { id: 6 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2025,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 30,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 30,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
      {
        user: { id: 3 },
        property: { id: 6 },
        noOfShare: 1,
        acquisitionDate: new Date(Date.now()),
        isActive: true,
        year: 2026,
        peakAllottedNights: 14,
        peakUsedNights: 0,
        peakBookedNights: 0,
        peakCancelledNights: 0,
        peakLostNights: 0,
        peakRemainingNights: 14,
        peakAllottedHolidayNights: 1,
        peakUsedHolidayNights: 0,
        peakBookedHolidayNights: 0,
        peakRemainingHolidayNights: 1,
        peakCancelledHolidayNights: 0,
        peakLostHolidayNights: 0,
        offAllottedNights: 30,
        offUsedNights: 0,
        offBookedNights: 0,
        offCancelledNights: 0,
        offLostNights: 0,
        offRemainingNights: 30,
        offAllottedHolidayNights: 1,
        offUsedHolidayNights: 0,
        offBookedHolidayNights: 0,
        offRemainingHolidayNights: 1,
        offCancelledHolidayNights: 0,
        offLostHolidayNights: 0,
        lastMinuteAllottedNights: 8,
        lastMinuteUsedNights: 0,
        lastMinuteBookedNights: 0,
        lastMinuteRemainingNights: 8,
        maximumStayLength: 14,
        createdBy: { id: 1 },
        updatedBy: null,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
      },
    ]);
  } else {
    console.log('Data already exists in User Properties table');
  }
};
